import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/navbar/page";

export const metadata: Metadata = {
  title: "Z.U Mechanical Works",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased flex flex-col lg:flex-row w-screen h-screen overflow-hidden`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
